services:
  - type: web
    name: fiesta-back
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: TYPEORM_SYNCHRONIZE
        value: "true"
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: API_BASE_URL
        sync: false
